# syntax=docker/dockerfile:1

FROM python:3.8:10

# WORKDIR /

# COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 5672 

# RUN pip install requests

# ADD wait-for-it.sh /
# RUN chmod u+x ./wait-for-it.sh

# CMD ["./wait-for-it.sh","rabbit:5672","--","python3","producer.py"]